### ISSUE TITLE
OSX Support

### ISSUE THREAD

**Issue by vs49688** [vs49688/RAFTools#2]
Considering RAFTools runs on OSX, support for opening the .app package should probably be implemented.

**Comment by vs49688** [comment]
I don't have a Mac to test it on, so I'm going to need a directory listing of the .app package

**Comment by vmattwin** [comment]
I ls -aR'd the league app, finding out how to post it

**Comment by vmattwin** [comment]
http://pastebin.pw/673/

**Comment by vmattwin** [comment]
I just realized the paste cuts off.

**Comment by vmattwin** [comment]
![lsout](https://cloud.githubusercontent.com/assets/15121319/10479089/c161e1ea-7216-11e5-9778-0f0e076a12dc.png)

(rename that to a zip to get whats inside)

**Comment by vmattwin** [comment]
https://mega.nz/#!X9lmVbaB

**Comment by vs49688** [comment]
It's asking for a decryption key. IIRC, you should be able to just drag the file into the comment box.

**Comment by vmattwin** [comment]
https://mega.nz/#!X9lmVbaB!DN3OSokHbqsp-tv6o9kwUyRKo0v1zhCr7mmXl6V_UAg

Sorry, I messed up the link.
If I click and drag github gives an unknown error.

**Comment by vs49688** [comment]
I've done the initial implementation, was pretty straightforward - just append "Contents/LoL" to the path and it's the same as opening a Windows LoL directory.

**Comment by vmattwin** [comment]
There's a new issue. 
![screen shot 2015-10-15 at 12 54 28 pm](https://cloud.githubusercontent.com/assets/15121319/10525839/e6153fb6-733b-11e5-9a1c-da083150af82.png)

I can't open the package with the menu option because I can't select the .app package. It's greyed out.

**Comment by vmattwin** [comment]
However, entering "openapp '/Applications/League of Legends.app/'" causes it to open.

**Comment by vs49688** [comment]
Okay, so it's a GUI issue then, I'll look into it a bit later today

**Comment by vs49688** [comment]
Are you able to build and run the code? I have a fix, however can't test is as I don't have a Mac

**Comment by vmattwin** [comment]
I've got the latest github code build + running.

**Comment by vs49688** [comment]
Okay, terriffic. When I get home, I'll create a branch and push the fix to it. Then you can build it from that branch before I merge it into master.

**Comment by vmattwin** [comment]
Fix confirmed. LoL app directory was both selectable and loading properly
