### ISSUE TITLE
LoL PBE problems

### ISSUE THREAD

**Issue by coldAmphibian** [vs49688/raftools#5]
Program detects folder that doesn't exist
![image](https://cloud.githubusercontent.com/assets/8411784/8392929/64aaa514-1d3d-11e5-82e1-7ff079a70729.png)
this happens for the pbe

**Comment by vs49688** [comment]
Downloading the PBE now to test it. I'm on Linux currently, so there may be some issues with updating it. Are you absolutely sure that the folder doesn't exist? If so, this might be some weird issue with the IPv4Sorter class

**Comment by vs49688** [comment]
Worked fine for me:
![2015-06-28-121441_700x500_scrot](https://cloud.githubusercontent.com/assets/4423262/8394863/5c6d341e-1d8f-11e5-9906-805c12f7b432.png)

**Comment by vs49688** [comment]
Confirmed, not a bug. You have a .raf file without a .raf.dat or vice versa.
