### ISSUE TITLE
Can't build properly on OSX

### ISSUE THREAD

**Issue by Rested** [vs49688/RAFTools#8]
Trying to build from source on osx since the link to the binary seems to be down but when I try to do the `gradle run` step I get 

> 'run' not found in root project 'RAFTools'.

**Comment by Rested** [comment]
and when i try to click on a dds file after running from `bin/lib/` i get 

> Exception in thread "AWT-EventQueue-0" java.nio.BufferUnderflowException
> 	at java.nio.Buffer.nextGetIndex(Buffer.java:506)
> 	at java.nio.HeapByteBuffer.getInt(HeapByteBuffer.java:361)
> 	at net.vs49688.rafview.dds.DDSImage$Header.read(DDSImage.java:610)
> 	at net.vs49688.rafview.dds.DDSImage.readFromBuffer(DDSImage.java:714)
> 	at net.vs49688.rafview.dds.DDSImage.read(DDSImage.java:195)
> 	at net.vs49688.rafview.gui.DDSViewer.setDDS(DDSViewer.java:68)
> 	at net.vs49688.rafview.gui.Controller$DDSDelayedLoader.lambda$load$0(Controller.java:394)
> 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
> 	at java.awt.EventQueue.access$500(EventQueue.java:97)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.awt.EventQueue$3.run(EventQueue.java:703)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

<img width="700" alt="screen shot 2017-03-22 at 22 11 13" src="https://cloud.githubusercontent.com/assets/2003608/24220880/58e3a890-0f4c-11e7-957b-7ac7068a16bf.png">

**Comment by vs49688** [comment]
Right, so in regards to the first one, it's not actually possible to run it directly via Gradle. I usually just run ```gradle jar``` and use the JAR file.

As for the DDS issue, it's possible that it's in a format that's not supported by the loader. Does this problem occur with all DDS files, or just that one? Try loading one of the champion splashes that appear on the loading screen - they should work.
